lib: func add prefix

diff --git a/lib b/lib
--- a/lib
+++ b/lib
@@ -35,13 +35,13 @@
 #         }
 
 ### Output version and exit.
-lib_version() {
+_lib_version() {
     printf "0.18.3\n" >&2;
     return 0
 }
 
 ### Create ISO by directory ##Usage: udf [dir_path]
-lib_udf() {
+_lib_udf() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
     [ -d "$1" ] || exit 1; # directory not found
     # hdiutil makehybrid -iso -joliet -o win8.iso win8.cdr
@@ -50,7 +50,7 @@ lib_udf() {
 }
 
 ### Cursor # ##Usage: cur [option] ##    --hide, -    hidden cursor#    --show, +    show cursor ##
-lib_cur() {
+_lib_cur() {
     case $1 in
         -|--hide)
             printf '\033[?25l'
@@ -70,7 +70,7 @@ lib_cur() {
 }
 
 ### Get apk file from AppStore ##Usage: gpkg [[countdown_sec]] #    1. Login AppStore and Install App #    2. Run this command before download complete #    3. Keep shell open
-lib_gpkg() {
+_lib_gpkg() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
     # sudo chown -R $USER:`id -gn $USER` /private/var/folders
     # sudo chmod -R 755 /private/var/folders
@@ -129,13 +129,13 @@ lib_gpkg() {
         sleep 1;
     done;
 
-    } | lib_prefix "%F %T, GPKG, "
+    } | _lib_prefix "%F %T, GPKG, "
 
     # wait all thread over
     wait
 }
 
-# for lib_gpkg
+# for _lib_gpkg
 # Override pkg map: pkg[$serial_number]="$path"
 __gpkg_serial_number() {
     local k v;
@@ -146,7 +146,7 @@ __gpkg_serial_number() {
     return 0
 }
 
-# for lib_gpkg
+# for _lib_gpkg
 # hash and move to ~/Downloads
 __gpkg_complete() {
     [ -f "$1" ] || return 1;
@@ -159,8 +159,8 @@ __gpkg_complete() {
         printf "SIZE: ";
         du -h "$1" | awk '{print $1}'
         printf "TIME: ";
-        lib_encode --dhms $(($(date +%s) - $sec_on));
-        lib_files --sums "$1"
+        _lib_encode --dhms $(($(date +%s) - $sec_on));
+        _lib_files --sums "$1"
         mv "$1" ~/Downloads 2>/dev/null || {
             cp "$1" ~/Downloads && printf "\033[31m$1 still exist\033[0m\n"
         }
@@ -169,10 +169,10 @@ __gpkg_complete() {
 }
 
 ### Encode string ##Usage: encode [option] [args...] ##    --dhms,   -t   [secends]    Format Unix timestamp to ??d ??h ??m ??s #    --passwd, -pw  [passwd_str] Get password for stdin chpasswd -e ##
-lib_encode() {
+_lib_encode() {
     case $1 in
         --dhms|-t)
-            lib_inum $2 || exit 1; # Not number
+            _lib_inum $2 || exit 1; # Not number
             local out=$(($2 % 60))s;
             [ $2 -ge 60 ] && {
                 out=$(($2 % 3600 / 60))m\ $out;
@@ -195,7 +195,7 @@ lib_encode() {
 }
 
 ### Create/Convert DMG file ##Usage: dmg [options] [path] ##    --create,  -c  [folder]          Create DMG #    --verify,  -t  [dmg_file]        verify dmg #    --dmg2iso, -di [dmg_file_path]   Convert a DMG file to ISO #    --iso2dmg, -id [iso_file_path]   Convert an ISO file to DMG format #    --createinstallmedia, -im [device_path] #                                     Create instatll media, by Install*.app #    --dd, -w       [img_path] [disk_path] #                                     Write img to disk ##
-lib_dmg() {
+_lib_dmg() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
     local tmp;
     case $1 in
@@ -268,7 +268,7 @@ lib_dmg() {
                     rm "${1%.*}.dmg";
                     # sudo dd if="${1%.*}.dmg" of=$target bs=4m & while killall -USR1 dd; do
                     #     sleep 10;
-                    # done | lib_prefix "%F %T, "
+                    # done | _lib_prefix "%F %T, "
                 ;;
                 gz)
                     which gzcat >/dev/null 2>&1 || exit 1; # gzcat command not found
@@ -296,7 +296,7 @@ lib_dmg() {
 }
 
 ### Remote tools ##Usage: remote [option] [args...] ##    -rsa [[user@]host] [[alias]]  Copy rsa public key to remote #    -tar [option] [[user@host:]target_path] [[user@host:]source_path] #                                  remote tar command #    -scp [pass_word] [command...] Auto scp with password ##
-lib_remote() {
+_lib_remote() {
     case $1 in
         -rsa)
             shift;
@@ -316,7 +316,7 @@ lib_remote() {
     esac
 }
 
-# for lib_remote
+# for _lib_remote
 __remote_rsa() {
      [ "$1" ] || exit 1; # first args is empty
     local rsa_pub;
@@ -339,7 +339,7 @@ chmod 700 ~/.ssh
     return 0
 }
 
-# for lib_remote
+# for _lib_remote
 __remote_auto_scp() {
     local password;
     password=$1;
@@ -471,7 +471,7 @@ __tar_cat_o() {
 
 
 ### OS globle setting ##Usage: oset [option] [args...] ##    --allow,     -a          Allow all app install #    --hidden,    - [yes|no]  Hidden all privite file or directory #    --re-launch, -rl         Reset LaunchPad ##
-lib_oset() {
+_lib_oset() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
     case $1 in
         --allow|-a)
@@ -492,7 +492,7 @@ lib_oset() {
 }
 
 ### File / directory tools ##Usage: files [option] [args...] ##    --unhidden, -uh [dir_path]   No hidden directory #    --own           [dir_path]   Set directory owner #    --boot          [dir_path]   Rebuild boot file #    --sums,  -s     [file_path]  Print md5 sha1 sha256 checksums #    --count, -c     [[dir_path]] get file count##
-lib_files() {
+_lib_files() {
     case $1 in
         -uh|--unhidden)
             shift;
@@ -548,7 +548,7 @@ lib_files() {
 }
 
 ### String filter ##Usage: filter [option] ##    --lower,    -l   [str]        Convert lower case #    --upper,    -r   [str]        Convert upper case #    --xmlvalue, -xv  [tag_name]   Get xml value #    --unascii,  -ua  [dir_path]   Print text not in ASCII char #    --tailto,    -t  [text_file] [line_num] #                                  save tail n line ##
-lib_filter() {
+_lib_filter() {
     case $1 in
         -l|--lower)
             shift;
@@ -593,7 +593,7 @@ lib_filter() {
         -t|--tailto)
             shift;
             [ -f "$1" ] || exit 1; # File not found
-            lib_inum $2 || exit 1; # Not number
+            _lib_inum $2 || exit 1; # Not number
             [ "$2" -gt 0 ] 2>/dev/null || exit 1; # Num too small
             mv "$1" "$1.swp";
             tail -$2 "$1.swp" > "$1";
@@ -606,13 +606,13 @@ lib_filter() {
 }
 
 ### Print random string match [A-Za-z0-9] ##Usage: rand [[size]]
-lib_rand() {
+_lib_rand() {
     # local rand=`dd if=/dev/random bs=1 count=${1:-32} 2>/dev/null | base64 | tr -d '\n'`; # tr -d '\n' support linux
     openssl rand -base64 ${1:-9} | tr -d '\n' | sed "s/[^0-9A-Za-z]/${RANDOM:0:1}/g"
 }
 
 ### Show/find IPv4 ##Usage: ip [option] [args...] ##    --list, -l            Show IPv4 #    --find, -f [mac_addr] Search IPv4 by MAC or Host name, #                          support alias, see lib hosts #    --test, -t [str]      Test string is ipv4 ##
-lib_ip() {
+_lib_ip() {
     case $1 in
         -l|--list)
             # netstat -rn | grep "default"
@@ -645,7 +645,7 @@ lib_ip() {
     esac
 }
 
-# for lib_ip
+# for _lib_ip
 __ip_find() {
     [ "$1" ] || exit 1; # MAC addr or Host name is empty
 
@@ -685,7 +685,7 @@ __ip_find() {
             # cache max variable length
             [ ${#i} -gt $l ] && l=${#i};
             # convert lowercase
-            macs=`lib_filter -l $macs`;
+            macs=`_lib_filter -l $macs`;
             # trim ^0
             for j in {0..9} {a..f}; do
                 macs=${macs//0$j/$j};
@@ -758,7 +758,7 @@ __hosts() {
 }
 
 ### Update hosts by ini #    will read ini config from HOME or script path. #    ini file context like: # #[hosts] #abc.org=01-12-23-34-45-56 #lib-233=67-78-89-9a-ab-bc #www.a.com=192.168.1.1 ##
-lib_hosts() {
+_lib_hosts() {
     source "$(cd `dirname $0`; pwd)/_function";
 
     # load ini in map1
@@ -774,7 +774,7 @@ lib_hosts() {
             _map -p $i 1;
             echo "$i"
         }
-    done < <(lib_ip --find ${REPLY[@]});
+    done < <(_lib_ip --find ${REPLY[@]});
 
     # clear map0, sip command use it before
     _map -c;
@@ -783,7 +783,7 @@ lib_hosts() {
     _map -a 1 || exit 1; # Unknown error
 
     for ((i=0; i<${#REPLY[@]}; i+=2)); do
-        lib_ip --test ${REPLY[i + 1]} && _map -p "${REPLY[$i]}" "${REPLY[i + 1]}";
+        _lib_ip --test ${REPLY[i + 1]} && _map -p "${REPLY[$i]}" "${REPLY[i + 1]}";
     done
 
     while read i; do
@@ -822,29 +822,29 @@ __imac() {
 }
 
 ### Connect vnc server ##Usage: vnc [ipv4][:[port]] ##server listening port 5900 ##
-lib_vnc() {
+_lib_vnc() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
-    lib_ip --test $1 || exit 1; # Args not a ipv4
+    _lib_ip --test $1 || exit 1; # Args not a ipv4
     open vnc://$1;
     return 0
 }
 
 ### Test str is num ##Usage: inum [str] ##
-lib_inum() {
+_lib_inum() {
     [ "$1" ] || return 2;
     [[ $1 != *[^0-9]* && $1 != 0[0-9]* ]] || return 1;
     return 0
 }
 
 ### Tag prefix each line, support `date` format ##Usage: [command] | prefix [strftime format] ##
-lib_prefix() {
+_lib_prefix() {
     [ "$1" ] || exit 1; # Args is empty
     source "$(cd `dirname $0`; pwd)/_function";
     _prefix "$@"
 }
 
 ### Plist editer ##Usage: plist [option] [path...] ##    --xml,    -x [plist_path]   print plist as xml format #    --json,   -j [plist_path]   print plist as xml format #    --binary, -b [plist_path]   serialize plist to stdout #    --load       [plist_path]   load plist #    --unload     [plist_path]   unload plist ##
-lib_plist() {
+_lib_plist() {
     [[ $OSTYPE == darwin* ]] || exit 1; # Only support OS X (macOS)
     which plutil >/dev/null 2>&1 || xcode-select --install 2>/dev/null
     [ $# -lt 2 ] && exit 1; # invalid option
@@ -898,7 +898,7 @@ __load_ini() {
 
     # # read environment variable
     # while read l tag; do
-    #     lib_ip --test $tag || {
+    #     _lib_ip --test $tag || {
     #         __imac $tag || continue
     #     };
     #     _map -p "$l" "$tag" $2;
@@ -937,8 +937,8 @@ __ramfs() {
 # # # # # # # # # # # # # # # # # # # # # # # # #
 
 # Print Error info
-func_err() {
-    [[ "$4_$6" == exit_${0##*/}* ]] && {
+_func_err() {
+    [[ "$4$6" == exit_${0##*/}* ]] && {
         local err=`awk 'NR=='$2'{print}' $0`;
         # Print line text after '#'
         printf "\033[31mError:${err##*#} \033[33m($0:$2)\033[0m\n" >&2;
@@ -959,7 +959,7 @@ func_err() {
 }
 
 # Show function info
-func_annotation() {
+_func_annotation() {
     local i j k OLDIFS IFS=$IFS\({;
     # Cache IFS
     OLDIFS=$IFS;
@@ -975,7 +975,7 @@ func_annotation() {
                 IFS=$OLDIFS
             };
             # At target func name
-            [ "$k" -a "$i" == "${0##*/}_$1" ] && {
+            [ "$k" -a "$i" == "_${0##*/}_$1" ] && {
                 # Print all annotation
                 for i in ${!k[@]}; do
                     printf "${k[$i]}\n";
@@ -983,7 +983,7 @@ func_annotation() {
                 return 0
             };
             # Reset var
-            [ "${i%%_*}" == "${0##*/}" -a "$j" == ")" ] && unset k;
+            [[ "$i" == _${0##*/}* ]] && [ "$j" == ")" ] && unset k;
         done < "$0"; # Scan this script
         return 1
     } || {
@@ -992,7 +992,7 @@ func_annotation() {
             # Cache intro
             [ "$i" == "###" ] && k=${j%%#*};
             # At func name
-            [ "${i%_*}" == "${0##*/}" -a "$j" == ")" ] && {
+            [ "${i%_*}" == "_${0##*/}" -a "$j" == ")" ] && {
                 # Left aligned at 15 char
                 printf "%-15s$k\n" ${i##*_};
                 # Clear var
@@ -1004,7 +1004,7 @@ func_annotation() {
 }
 
 # Cache exit
-trap 'func_err $? $LINENO $BASH_LINENO $BASH_COMMAND ${FUNCNAME[@]}' EXIT
+trap '_func_err $? $LINENO $BASH_LINENO $BASH_COMMAND ${FUNCNAME[@]}' EXIT
 
 # # # # # # # # # # # # # # # # # # # # # # # # #
 #                   Framework                   #
@@ -1012,18 +1012,18 @@ trap 'func_err $? $LINENO $BASH_LINENO $BASH_COMMAND ${FUNCNAME[@]}' EXIT
 
 # Test if help
 [[ ! "$1" || "$1" == "-h" || "$1" == "--help" ]] && {
-    func_annotation | sort;
+    _func_annotation | sort;
     exit 0
 } || [[ "$2" == "-h" || "$2" == "--help" ]] && {
     # Test if help
-    func_annotation $1 || printf "\033[31mError: No function found \033[0m\n" >&2;
+    _func_annotation $1 || printf "\033[31mError: No function found \033[0m\n" >&2;
     exit $?
 };
 
 # $*, "$*", $@ can not keep $#, only "$@" can save native structural
 
 # main
-${0##*/}_"$@"
+_${0##*/}_"$@"
 
 # hdiutil attach *.dmg
 # hdiutil detach *.dmg
